---
- name: setup wsl
  hosts: localhost
  become: true

  pre_tasks:
    - name: upgrade apt repositories
      apt:
        update_cache: true

  roles:
    - misc
    - vim
    - tmux
    - tanzu

  post_tasks:
    - name: cleanup apt packages
      apt:
        autoclean: true
        autoremove: true
